version: '3.2'

services:

  foo:
    build:
      context: ./foo
      dockerfile: Dockerfile
    volumes:
      - ./foo:/app

  bar:
    build:
      context: ./bar
      dockerfile: Dockerfile
    volumes:
      - ./bar:/app