version: '3.2'

services:

  foo:
    build:
      context: ./foo
      dockerfile: Dockerfile
    command: npm run start
    environment:
      - PORT=3000
    volumes:
      - ./foo:/app

  bar:
    build:
      context: ./bar
      dockerfile: Dockerfile
    environment:
      - HOST=foo
      - PORT=3000
    volumes:
      - ./bar:/app